---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


## Import the 'FAS_litters.cvs' csv using a relative path. 
建议使用相对路径，从where you are开始(R project)

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)

```


## Import the same dataset using an absolute path(NOT suggest)

```{r}
litters_df_abs =
  read_csv("D:/Data Science/COURSE NOTE/Data_wrangling_01/data/FAS_litters.csv")
  
litters_df =
  janitor::clean_names(litters_df_abs)
```

## Import FAS_pups.csv dataset

```{r}
pups_dataframe = 
  read_csv("data/FAS_pups.csv")

pups_dataframe =
  janitor::clean_names(pups_dataframe)
```

## look at data

```{r}
litters_df_abs

head(litters_df)

tail(litters_df)
```

You can use 'view'

```{r, eval=FALSE}
view(litters_df)
```

# Look at a data summary

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in 'read_*'

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 10, col_names = FALSE)
```

#### Look at NA values

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("NA",19,"missing","."))
```

#### Column types

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    col_types = 
      cols(
        'GD0 weight' = col_factor()
      )
  )
```











